"""The online version: one web address for the dashboard (behind a password), the Claude connector
at /mcp (behind a sign-in), Instagram's connect flow, and video links Instagram downloads from.

The dashboard itself still runs as before, on an internal port; this gateway sits in front of it.
"""
from __future__ import annotations

import html
import os
import secrets
import threading
import time
from http.server import ThreadingHTTPServer
from pathlib import Path
from urllib.parse import quote, urlparse

import httpx
from mcp.server.auth.settings import AuthSettings, ClientRegistrationOptions, RevocationOptions
from mcp.server.fastmcp import FastMCP
from mcp.server.transport_security import TransportSecuritySettings
from starlette.background import BackgroundTask
from starlette.concurrency import run_in_threadpool
from starlette.requests import Request
from starlette.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse, Response, StreamingResponse

from . import instagram_auth, mcp_tools, security
from .config import set_env_values

HOP = {"connection", "keep-alive", "proxy-authenticate", "proxy-authorization", "te", "trailers", "transfer-encoding", "upgrade", "host"}

INSTRUCTIONS = """Reel Studio plans and publishes short vertical videos (Instagram Reels and Stories, YouTube Shorts).
Always call reelstudio_get_account first. You write the ideas, Flow prompts and captions yourself, matching the
person's recent captions. Videos are generated by the person in Google Flow, never by you. Never schedule a post
the person has not watched and approved in this conversation."""


def page(title: str, body: str) -> HTMLResponse:
    return HTMLResponse(f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>{html.escape(title)} · Reel Studio</title>
<style>
:root {{ --bg:#f6f7fb; --card:#fff; --text:#161a2b; --muted:#636b83; --border:#e4e7ef; --accent:#4f46e5; --on:#fff; --red:#b4262e; }}
@media (prefers-color-scheme: dark) {{ :root {{ --bg:#0e1020; --card:#171a2e; --text:#eceefa; --muted:#9aa2c0; --border:#2a2f4b; --accent:#7c74ff; --on:#0e1020; --red:#ff7a85; }} }}
* {{ box-sizing: border-box; }}
body {{ margin:0; min-height:100vh; display:grid; place-items:center; background:var(--bg); color:var(--text);
  font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Roboto,sans-serif; padding:16px; }}
.card {{ width:100%; max-width:400px; background:var(--card); border:1px solid var(--border); border-radius:16px; padding:28px;
  box-shadow:0 4px 24px rgba(0,0,0,.06); }}
.logo {{ width:40px; height:40px; border-radius:11px; background:linear-gradient(135deg,#6d5dfc,#3b82f6); display:grid; place-items:center; margin-bottom:16px; }}
h1 {{ font-size:20px; margin:0 0 6px; letter-spacing:-.01em; }} p {{ color:var(--muted); margin:0 0 18px; }}
label {{ display:block; font-size:13px; font-weight:600; margin-bottom:6px; }}
input {{ width:100%; padding:11px 12px; border:1px solid var(--border); border-radius:10px; background:var(--card); color:var(--text); font:inherit; margin-bottom:14px; }}
button, a.btn {{ display:block; width:100%; text-align:center; padding:11px; border:0; border-radius:10px; background:var(--accent); color:var(--on);
  font:inherit; font-weight:600; cursor:pointer; text-decoration:none; }}
button.ghost {{ background:transparent; color:var(--muted); margin-top:8px; }}
.err {{ color:var(--red); font-weight:600; }} code {{ word-break:break-all; }}
</style></head><body><div class="card"><div class="logo"><svg width="18" height="18" viewBox="0 0 24 24" fill="#fff"><path d="M5 3l14 9-14 9z"/></svg></div>
{body}</div></body></html>""")


def client_ip(request: Request) -> str:
    # The hosting provider's proxy appends the real address last; earlier entries can be forged.
    fwd = request.headers.get("x-forwarded-for")
    return fwd.split(",")[-1].strip() if fwd else (request.client.host if request.client else "?")


def build(app, internal_port: int, public_url: str, password: str) -> object:
    """Return the ASGI app. `app` is the dashboard App (shared settings, database, log)."""
    public_url = public_url.rstrip("/")
    host = urlparse(public_url).netloc
    data_dir = app.cfg.path("data")
    key = security.secret_key(data_dir)
    limiter = security.LoginLimiter()
    from .oauth import ReelStudioOAuth

    oauth = ReelStudioOAuth(data_dir / "auth.db", public_url)
    app.oauth = oauth
    ig_states: dict[str, float] = {}
    secure = public_url.startswith("https://")

    mcp = FastMCP(
        "reelstudio",
        instructions=INSTRUCTIONS,
        auth_server_provider=oauth,
        auth=AuthSettings(
            issuer_url=public_url,
            resource_server_url=f"{public_url}/mcp",
            client_registration_options=ClientRegistrationOptions(enabled=True),
            revocation_options=RevocationOptions(enabled=True),
            # Tokens are only ever issued by this server for this server, so no audience check is needed.
            validate_token_resource=False,
        ),
        streamable_http_path="/mcp",
        stateless_http=True,
        json_response=True,
        transport_security=TransportSecuritySettings(
            enable_dns_rebinding_protection=True,
            allowed_hosts=[host, f"{host}:*", "127.0.0.1:*", "localhost:*", "testserver"],
            allowed_origins=[public_url, "https://claude.ai", "https://claude.com"],
        ),
    )
    mcp_tools.register(mcp, app)
    upstream = httpx.AsyncClient(base_url=f"http://127.0.0.1:{internal_port}", timeout=httpx.Timeout(600, connect=10))

    def logged_in(request: Request) -> bool:
        return security.valid_session(key, request.cookies.get(security.SESSION_COOKIE))

    def check_password(request: Request, given: str) -> str | None:
        """None when correct, else the message to show."""
        who = client_ip(request)
        if limiter.blocked(who):
            return "Too many wrong attempts. Wait 15 minutes."
        if not security.check_password(given, password):
            limiter.fail(who)
            return "Wrong password."
        limiter.reset(who)
        return None

    def with_session(resp: Response) -> Response:
        resp.set_cookie(security.SESSION_COOKIE, security.make_session(key), max_age=security.SESSION_DAYS * 86400,
                        httponly=True, secure=secure, samesite="lax")
        return resp

    # ----- health -----
    @mcp.custom_route("/healthz", methods=["GET"])
    async def healthz(request: Request) -> Response:
        return JSONResponse({"ok": True})

    # ----- dashboard login -----
    def login_form(next_url: str, error: str = "") -> HTMLResponse:
        return page("Sign in", f"""<h1>Reel Studio</h1><p>Sign in to your dashboard.</p>
            {f'<p class="err">{html.escape(error)}</p>' if error else ''}
            <form method="post" action="/login"><input type="hidden" name="next" value="{html.escape(next_url)}">
            <label for="pw">Password</label><input id="pw" name="password" type="password" autocomplete="current-password" autofocus required>
            <button type="submit">Sign in</button></form>""")

    def safe_next(n: str) -> str:
        return n if n.startswith("/") and not n.startswith("//") else "/"

    @mcp.custom_route("/login", methods=["GET", "POST"])
    async def login(request: Request) -> Response:
        if request.method == "GET":
            return login_form(safe_next(request.query_params.get("next", "/")))
        form = await request.form()
        nxt = safe_next(str(form.get("next", "/")))
        if err := check_password(request, str(form.get("password", ""))):
            return login_form(nxt, err)
        return with_session(RedirectResponse(nxt, status_code=303))

    @mcp.custom_route("/logout", methods=["GET"])
    async def logout(request: Request) -> Response:
        resp = RedirectResponse("/login", status_code=303)
        resp.delete_cookie(security.SESSION_COOKIE)
        return resp

    # ----- Claude connector sign-in -----
    @mcp.custom_route("/connect-claude", methods=["GET", "POST"])
    async def connect_claude(request: Request) -> Response:
        req = request.query_params.get("req") if request.method == "GET" else str((await request.form()).get("req", ""))
        pending = oauth.pending_request(req or "")
        if not pending:
            return page("Expired", "<h1>This link has expired</h1><p>Go back to Claude and press Connect again.</p>")
        client_id, params = pending
        client = await oauth.get_client(client_id)
        name = html.escape((client.client_name if client else None) or "An app")
        back_to = html.escape(urlparse(str(params.redirect_uri)).netloc)
        error = ""
        if request.method == "POST":
            form = await request.form()
            if form.get("action") == "deny":
                return RedirectResponse(oauth.deny(req) or "/", status_code=303)
            if not (error := check_password(request, str(form.get("password", ""))) or ""):
                app.say(f"{(client.client_name if client else 'An app')} connected to Reel Studio")
                return RedirectResponse(oauth.approve(req), status_code=303)
        return page("Connect", f"""<h1>Allow {name} to use Reel Studio?</h1>
            <p>It will be able to read your posts, plan new ones and schedule videos you approve. It will send you back to <b>{back_to}</b>.</p>
            {f'<p class="err">{html.escape(error)}</p>' if error else ''}
            <form method="post" action="/connect-claude"><input type="hidden" name="req" value="{html.escape(req)}">
            <label for="pw">Your Reel Studio password</label><input id="pw" name="password" type="password" autocomplete="current-password" autofocus>
            <button type="submit" name="action" value="allow">Allow</button>
            <button type="submit" name="action" value="deny" class="ghost" formnovalidate>Cancel</button></form>""")

    # ----- Instagram connect (your own Meta app) -----
    redirect_uri = f"{public_url}/oauth/instagram/callback"
    app.ig_redirect_uri = redirect_uri

    @mcp.custom_route("/oauth/instagram/start", methods=["GET"])
    async def ig_start(request: Request) -> Response:
        if not logged_in(request):
            return RedirectResponse("/login?next=/oauth/instagram/start", status_code=303)
        app_id = os.environ.get("IG_APP_ID")
        if not app_id or not os.environ.get("IG_APP_SECRET"):
            return page("Instagram", '<h1>Add your Meta app first</h1><p>Paste the Instagram App ID and App Secret in Settings, save, then press Connect again.</p><a class="btn" href="/#settings">Back to Settings</a>')
        now = time.time()
        for k in [k for k, t in ig_states.items() if now - t > 900]:
            ig_states.pop(k)
        state = secrets.token_urlsafe(24)
        ig_states[state] = now
        return RedirectResponse(instagram_auth.authorize_url(app_id, redirect_uri, state), status_code=303)

    @mcp.custom_route("/oauth/instagram/callback", methods=["GET"])
    async def ig_callback(request: Request) -> Response:
        if not logged_in(request):
            return RedirectResponse("/login", status_code=303)
        q = request.query_params
        if q.get("error"):
            return page("Instagram", f'<h1>Not connected</h1><p>{html.escape(q.get("error_description") or q.get("error"))}</p><a class="btn" href="/#settings">Back to Settings</a>')
        if not q.get("state") or ig_states.pop(q.get("state"), None) is None:
            return page("Instagram", '<h1>That link expired</h1><p>Press Connect Instagram again.</p><a class="btn" href="/#settings">Back to Settings</a>')
        try:
            values = await run_in_threadpool(
                instagram_auth.connect, os.environ["IG_APP_ID"], os.environ["IG_APP_SECRET"], redirect_uri, q.get("code", ""))
        except (instagram_auth.InstagramAuthError, httpx.HTTPError, Exception) as e:
            return page("Instagram", f'<h1>Not connected</h1><p>{html.escape(str(e))}</p><a class="btn" href="/#settings">Back to Settings</a>')
        account_type = values.pop("_account_type", "")
        set_env_values(app.config_path.parent / ".env", values)
        app.enable_instagram_api()
        app.say(f"Instagram connected as @{values['IG_USERNAME']}")
        warn = "" if account_type in ("", "BUSINESS", "MEDIA_CREATOR", "CREATOR") else \
            f"<p class='err'>Instagram reports this as a {html.escape(account_type)} account. Publishing needs a Business or Creator account.</p>"
        return page("Instagram", f'<h1>Instagram connected</h1><p>Signed in as <b>@{html.escape(values["IG_USERNAME"])}</b>. Approved posts will now go out automatically.</p>{warn}<a class="btn" href="/#settings">Back to Settings</a>')

    # ----- video links for Instagram to download -----
    @mcp.custom_route("/public-media/{post_id}/{sig}.mp4", methods=["GET", "HEAD"])
    async def public_media(request: Request) -> Response:
        pid, sig = request.path_params["post_id"], request.path_params["sig"]
        if not secrets.compare_digest(sig, security.media_signature(key, pid)):
            return Response(status_code=404)
        s = app.store()
        try:
            post = s.get(pid)
        except KeyError:
            return Response(status_code=404)
        finally:
            s.close()
        path = Path(post["final_path"] or "")
        if not path.is_file():
            return Response(status_code=404)
        return FileResponse(path, media_type="video/mp4")

    app.media_url_for = lambda pid: f"{public_url}/public-media/{quote(pid)}/{security.media_signature(key, pid)}.mp4"

    # ----- everything else: the dashboard, after sign-in -----
    @mcp.custom_route("/{path:path}", methods=["GET", "POST", "PUT", "HEAD"])
    async def dashboard(request: Request) -> Response:
        if not logged_in(request):
            if request.url.path.startswith(("/api/", "/media/")):
                return JSONResponse({"error": "Signed out. Reload the page and sign in."}, status_code=401)
            nxt = request.url.path + (f"?{request.url.query}" if request.url.query else "")
            return RedirectResponse(f"/login?next={quote(nxt)}", status_code=303)
        headers = {k: v for k, v in request.headers.items() if k.lower() not in HOP and k.lower() != "cookie"}
        headers["host"] = f"127.0.0.1:{internal_port}"
        body = request.stream() if request.method in ("POST", "PUT") else None
        req = upstream.build_request(request.method, request.url.path, params=request.url.query or None, headers=headers, content=body)
        resp = await upstream.send(req, stream=True)
        out = {k: v for k, v in resp.headers.items() if k.lower() not in HOP}
        return StreamingResponse(resp.aiter_raw(), status_code=resp.status_code, headers=out, background=BackgroundTask(resp.aclose))

    return mcp.streamable_http_app()


def serve(config_path: str, port: int, public_url: str, password: str) -> None:
    import logging

    import uvicorn

    logging.getLogger("httpx").setLevel(logging.WARNING)  # one line per proxied request is just noise

    from .ui import App, make_handler, prepare_app

    app: App = prepare_app(config_path)
    app.public_url = public_url.rstrip("/")
    internal = ThreadingHTTPServer(("127.0.0.1", 0), make_handler(app))
    threading.Thread(target=internal.serve_forever, daemon=True).start()
    asgi = build(app, internal.server_address[1], public_url, password)
    threading.Thread(target=app.background, daemon=True).start()
    print(f"Reel Studio online at {public_url} (listening on port {port})", flush=True)
    uvicorn.run(asgi, host="0.0.0.0", port=port, proxy_headers=True, forwarded_allow_ips="*", log_level="warning")
